<a href="https://colab.research.google.com/github/warwickdatascience/beginners-python/blob/master/session_four/session_four_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>Spotted a mistake? Report it <a href="https://github.com/warwickdatascience/beginners-python/issues/new">here</a></center>

# Beginner's Pythonâ€”Session Four Homework Exercises

## Non-numeric Lists

Ask the user to input 3 days of the week (using `input()` three times) and use these to create a list of strings

In [ ]:
a=input("Enter a day ")
b=input("Enter a day ")
c=input("Enter a day ")
d=[a,b,c]
print("Days are ",d)

Enter a daysunday
Enter a daymonday
Enter a daytuesday
Days are  ['sunday', 'monday', 'tuesday']

Create a list containing three lists. The first list should contain the numbers $1$ to $3$, the second should contain the English forms (e.g. "one") of these words. And the last should contain Boolean values which are True if the corresponding number is prime (hint: $1$ is not prime, $2$ and $3$ are)

In [ ]:
a=[[1,2,3],["one","two","three"],["false","true","true"]]
print (a)

[[1, 2, 3], ['one', 'two', 'three'], ['false', 'true', 'true']]

Lists of lists don't have to be square. Create a list containing lists of length $1$, $2$, and $3$, each filled with numbers of your choosing

In [ ]:
b=[1,[2,3],[4,5,6]]

## Extracting List Elements

Run the following code to generate a list of random numbers with a length randomly chosen between 50 and 100

In [ ]:
from random import random, randint, seed
seed(1729)
numbers = [random() for __ in range(randint(50, 100))]

What is the 42nd element of this list?

In [ ]:
print(numbers[41])

0.23234868054280078

What is the value of the element that is tenth from the end of the list?

In [ ]:
print(numbers[-10])

0.2680869869099519

What happens when you try to access the value of an index that doesn't exist?

In [ ]:
print(numbers[101])

IndexError: ignored

_This is quite a tough challenge, but try to persevere. You can always check out the solutions if you're unsure_

The following code will create a reordering of the numbers 0 to 99

In [ ]:
from random import shuffle, seed
mapping = [i for i in range(100)]
seed(1729)
shuffle(mapping)
print(mapping)

[69, 56, 2, 32, 67, 62, 93, 89, 4, 59, 10, 75, 15, 87, 16, 76, 8, 40, 34, 24, 94, 55, 39, 22, 99, 79, 98, 88, 49, 42, 1, 31, 3, 72, 20, 81, 60, 43, 33, 53, 91, 41, 9, 57, 74, 68, 35, 18, 29, 11, 13, 71, 25, 17, 65, 14, 27, 73, 86, 30, 96, 61, 54, 80, 90, 82, 44, 38, 48, 12, 6, 92, 51, 28, 84, 77, 97, 45, 50, 47, 95, 78, 0, 63, 70, 19, 26, 36, 46, 66, 37, 23, 7, 85, 21, 58, 64, 52, 5, 83]

You can think of this as a sort of mapping, where the value of a given index tells you which index to look at next. For example index zero contains the value $26$ so we'd next look at index $26$. This has value $60$ so we'd then look at index $60$, etc.

It is not hard to show that if you continue following this rule, you'll eventually get back to where you started. It would be interesting to know how many steps this takes.

Ask the user for an index to start from and then follow the rule until you get back to the start, keeping track of how many steps this takes.

You will want to define a variable `steps` to keep track of how many steps you've taken as well as a variable `curr_value`, initial set to the starting value, to hold the current value you are looking at. You should keep looping until `curr_value == start_value` and `steps >= 1`. The last condition is needed to ensure that you don't immediately exit the loop. On each loop iteration you can increment the step count and update the current value to be `mapping[curr_value]`. Have a go at tying these ideas together into a solution.

In [ ]:
i=int(input("Enter a index "))
start_value=mapping[i]
steps=1
curr_value=mapping[start_value]
while curr_value != start_value:
  steps+=1
  curr_value=mapping[curr_value] 
print(steps)

Enter a index 3
2

(Fun fact: for a mapping with $n$ elements, the average chain length is roughly equal to $\frac{n}{\log(n)}$)

## Slicing Lists

Using the variable `numbers` from above, extract a sub-list containing the 5th to 15th elements

In [ ]:
nu=numbers[4:15]
print(nu)

[0.18251911452417136, 0.29217588543820794, 0.3630932932632249, 0.8671459725962595, 0.2076513315470634, 0.8289947875089807, 0.15602920092468964, 0.7308024134384177, 0.4997260049413905, 0.6133376468495829, 0.3703879594514147]

Extract a sub-list containing all of the 5 last elements except the actual last

In [ ]:
print(numbers[-6:-1])

[0.2739606889201578, 0.18997501537917683, 0.08899260541674403, 0.4722608870711954, 0.6845677309179482]

If I use the slice `m:n` with $m<n$, how many elements will the resulting list contain?

In [ ]:
print(len(numbers[4:5]),"n-m")

1 n-m

You are welcome to use variables as the indices for your slice.
* Create a list of 10 numbers
* Set a variable `n` to initially be 2
* Loop until `n` is greater than 5, incrementing `n` by one each time
* On each loop print out the results of taking the slice `n:8`

In [ ]:

mapping = [i for i in range(10)]
print(mapping)
n=2
while n < 6:
  n+=1
  print(mapping[n:8])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7]
[4, 5, 6, 7]
[5, 6, 7]
[6, 7]

## Manipulating Lists

Create an empty list called `squares` using `squares = []`

In [ ]:
squares=[]

Loop through the values 1 to 10, appending the square of this value to the list at each stage. Finish by printing out the variable

In [ ]:
for i in range(1,11):
  squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

You can check if a value is in a list using `val in my_list`. Use this idea alongside the method for removing by value to delete all instances of the word "spam" in the following list

In [ ]:
menu = ["Spam", "Sausage", "Spam", "Spam", "Spam", "Bacon", "Spam", "Tomato", "Spam"]

In [ ]:
while "Spam" in menu:
  menu.remove("Spam")
print (menu)

['Sausage', 'Bacon', 'Tomato']

Create a list of decimal numbers and loop through it, replacing each element with half its current value

In [ ]:
lis=[2.3,7.5,6.8]
for a,b in enumerate(lis):
 lis[a]=b/2
print (lis)

[1.15, 3.75, 3.4]

Beware: when you delete an element of a list, you will change its length and cause all elements after it to 'shuffle down'. Create a list of 8 numbers and delete every other element, starting with the first, using a while loop.

In [ ]:
li=[i for i in range(8)]
while len(li)!=0:
  li.remove(li[0])
  print(li)

[1, 2, 3, 4, 5, 6, 7]
[2, 3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[4, 5, 6, 7]
[5, 6, 7]
[6, 7]
[7]
[]

## Tuples

Create a tuple containing five numbers. Extract the last value using negative indexing

In [ ]:
tu=(1,2,3,4,5)
print(tu[-1])

5

Just like we can convert between data types using `int()`, `str()`, `float()` and `bool()`, we can convert between lists and tuples using `list()` and `tuple()`. Create a list, append a value, convert it to a tuple then attempt to append another value, confirming that this can't be done

In [ ]:
l=["a",2]
l.append(3)
print(l)
s=tuple(l)
#s.append(4)
print(s)

['a', 2, 3]
('a', 2, 3)

Repeat this in the opposite direction, starting with a tuple

In [ ]:
t=(1,20)
print(type(t))
v=list(t)
v.append(4)
print (v)

<class 'tuple'>
[1, 20, 4]